### ISSUE TITLE
url parameter app= className not working

### ISSUE THREAD

**Issue by choper725** [oblomov-dev/abap2UI5#221] opened 2023-05-12 08:17 UTC
hi there,
url parameter app=classname
not working

**Comment by oblomov-dev** [comment] 2023-05-12 08:35
how do you call it? 

Works fine for me:
<img width="908" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/b10df8ed-53c9-472e-8c1c-ace5157f4c51">

**Comment by choper725** [comment] 2023-05-12 08:49
i call it exacly like that, i even tr using the first screen to check the class and then clicking the link to open the url, im not getting the app for the inserted class, everytime the main window open(where you can check class or goto demos)
im on premise if that matters..

**Comment by oblomov-dev** [comment] 2023-05-12 08:58
I can only test in the cloud environment, but that should not matter.

can you pull the latest version (updated it right now).
then test it with the basic example:
<img width="769" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/155a9d71-53eb-4b44-9bdd-916c27f376f4">
And if it is not working set a breakpoint here:
<img width="994" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/985db3c1-7334-4038-b67d-4b512e619954">
line 1403 -> classname is read by url parameters
line 1411 -> instance is created with the classname

Somewhere there should be the problem. Let me know what happens in your situation.

**Comment by nomssi** [comment] 2023-05-15 22:40
I do not have/could not reproduce the original issue, if I enter an invalid class, the error message appears
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/452cc678-f804-4963-8e8e-4b8da0fa5811)

If press on HOME, the screen to select a class is displayed, but if I press on BACK, an internal error 500 occurs.

**Comment by oblomov-dev** [comment] 2023-05-16 05:58
I fixed the error view. No Back is only enabled when there is a previous app/screen:
<img width="633" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/0a7de95a-613a-4796-a326-7c1651628faa">

**Comment by oblomov-dev** [comment] 2023-05-26 18:23
i close this issue, if there are still problems, please open a new one.

**Closed by oblomov-dev** 2023-05-26 18:23 UTC
